networks:
  autoacervus-net:
    driver: bridge
    name: autoacervus-net
services:
  mysql:
    image: mysql:8.0.37-debian
    container_name: autoacervus-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoacervus
      MYSQL_USER: autoacervus
      MYSQL_PASSWORD: autoacervus
    ports:
      - 3306:3306
    networks:
      - autoacervus-net
    volumes:
      - ./db:/var/lib/mysql
      - ./src/main/sql/autoacervus-db-creation_script.sql:/docker-entrypoint-initdb.d/1.sql
  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoacervus-java
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - autoacervus-net
    env_file:
      - .env
    depends_on:
      - mysql
