-- MySQL Script generated by MySQL Workbench
-- ter 21 mai 2024 23:42:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autosbu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autosbu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autosbu` ;
USE `autosbu` ;

-- -----------------------------------------------------
-- Table `autosbu`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosbu`.`Users` ;

CREATE TABLE IF NOT EXISTS `autosbu`.`Users` (
  `emailDac` VARCHAR(30) NOT NULL,
  `sbuPassword` CHAR(6) NOT NULL,
  PRIMARY KEY (`emailDac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosbu`.`BorrowedBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosbu`.`BorrowedBooks` ;

CREATE TABLE IF NOT EXISTS `autosbu`.`BorrowedBooks` (
  `borrower` VARCHAR(30) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `code` INT NOT NULL,
  `registryCode` INT NOT NULL,
  `expectedReturnDate` DATE NOT NULL,
  `canRenew` TINYINT NOT NULL,
  INDEX `fk_borrower_idx` (`borrower` ASC) VISIBLE,
  PRIMARY KEY (`code`, `registryCode`, `borrower`),
  CONSTRAINT `fk_borrower`
    FOREIGN KEY (`borrower`)
    REFERENCES `autosbu`.`Users` (`emailDac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
