-- MySQL Script generated by MySQL Workbench
-- sex 07 jun 2024 14:34:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoacervus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoacervus` ;

-- -----------------------------------------------------
-- Schema autoacervus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoacervus` ;
USE `autoacervus` ;

-- -----------------------------------------------------
-- Table `autoacervus`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoacervus`.`Users` ;

CREATE TABLE IF NOT EXISTS `autoacervus`.`Users` (
  `emailDac` VARCHAR(30) NOT NULL,
  `sbuPassword` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`emailDac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoacervus`.`BorrowedBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoacervus`.`BorrowedBooks` ;

CREATE TABLE IF NOT EXISTS `autoacervus`.`BorrowedBooks` (
  `borrower` VARCHAR(30) NOT NULL,
  `code` INT NOT NULL,
  `registryCode` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `expectedReturnDate` DATE NOT NULL,
  `canRenew` TINYINT NOT NULL,
  INDEX `fk_borrower_idx` (`borrower` ASC) VISIBLE,
  PRIMARY KEY (`borrower`, `code`, `registryCode`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `registryCode_UNIQUE` (`registryCode` ASC) VISIBLE,
  CONSTRAINT `fk_borrower`
    FOREIGN KEY (`borrower`)
    REFERENCES `autoacervus`.`Users` (`emailDac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
