-- MySQL Script generated by MySQL Workbench
-- sex 14 jun 2024 19:23:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoacervus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoacervus` ;

-- -----------------------------------------------------
-- Schema autoacervus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoacervus` ;
USE `autoacervus` ;

-- -----------------------------------------------------
-- Table `autoacervus`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoacervus`.`Users` ;

CREATE TABLE IF NOT EXISTS `autoacervus`.`Users` (
    `emailDac` VARCHAR(30) NOT NULL,
    `password` TEXT NOT NULL,
    PRIMARY KEY (`emailDac`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoacervus`.`BorrowedBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoacervus`.`BorrowedBooks` ;

CREATE TABLE IF NOT EXISTS `autoacervus`.`BorrowedBooks` (
    `borrower` VARCHAR(30) NOT NULL,
    `code` INT NOT NULL,
    `registryCode` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `expectedReturnDate` DATE NOT NULL,
    `canRenew` TINYINT NOT NULL,
    INDEX `fk_borrower_idx` (`borrower` ASC) VISIBLE,
    PRIMARY KEY (`borrower`, `code`, `registryCode`),
    UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
    UNIQUE INDEX `registryCode_UNIQUE` (`registryCode` ASC) VISIBLE,
    CONSTRAINT `fk_borrower`
    FOREIGN KEY (`borrower`)
    REFERENCES `autoacervus`.`Users` (`emailDac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoacervus`.`UserStats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoacervus`.`UserStats` ;

CREATE TABLE IF NOT EXISTS `autoacervus`.`UserStats` (
    `user` VARCHAR(30) NOT NULL,
    `renewalCount` INT NOT NULL,
    `signupDate` DATE NOT NULL,
    PRIMARY KEY (`user`),
    INDEX `fk_UserStats_Users1_idx` (`user` ASC) VISIBLE,
    CONSTRAINT `fk_UserStats_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `autoacervus`.`Users` (`emailDac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoacervus`.`UserSettings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoacervus`.`UserSettings` ;

CREATE TABLE IF NOT EXISTS `autoacervus`.`UserSettings` (
    `user` VARCHAR(30) NOT NULL,
    `receiveEmails` TINYINT NOT NULL,
    PRIMARY KEY (`user`),
    INDEX `fk_UserSettings_Users1_idx` (`user` ASC) VISIBLE,
    CONSTRAINT `fk_UserSettings_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `autoacervus`.`Users` (`emailDac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
